# NumPy

*   Instructor: Victor Fuentes Campos
*   Curso: Fundamentos de Programación en Python para las CCSS y Gestión Pública
*   Adapatado de las clases de Carla Solís y Alexander Quispe

Empecemos con un [video sencillo](https://www.youtube.com/watch?v=Tkv45wgxlEU)

> En adelante, empezamos a usar librarías de Python, que son como súperpoderes que catalizarán nuestras habilidades  de programación en Python. Estas funciona como plugins o extensinoes para hacer nuestro código más eficiente

[NumPy](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html) (Numerical Python) es la biblioteca central para la computación científica en Python. Proporciona un objeto array multidimensional de alto rendimiento y herramientas para trabajar con estos. Si ya estás familiarizado con MATLAB, es posible que encuentres útil este tutorial para comenzar con NumPy.

<img src="https://s3.amazonaws.com/dq-content/289/1.2-m289.gif" width="1000">

### Arrays
Un array de NumPy es una cuadrícula de valores, todos del mismo tipo, y se indexa mediante tuples de enteros no negativos. El número de dimensiones es el rango del array; la forma (shape) de un array es un tuple de enteros que indica el tamaño del array a lo largo de cada dimensión.

No olviden instalar numpy: ```conda install numpy```

In [ ]:
# En el cmd (windows), terminal (mac) o ananconda prompt (anaconda)
# conda install numpy
# o
# pip install numpy
import numpy as np

In [4]:
a = np.array( [1, 2, 3, 4, 5] )

In [5]:
a   

array([1, 2, 3, 4, 5])

In [6]:
type(a)

numpy.ndarray

In [7]:
# 1D array
a = np.array( [1, 2, 3, 4, 5] )
print(a)

[1 2 3 4 5]


In [8]:
# 2D array
M = np.array( [ [1, 2, 3], [4, 5, 6] ] )

print(M)

[[1 2 3]
 [4 5 6]]


In [9]:
X = np.array( [ [1, 2, 3, 4], [4, 5, 6, 7] ] )
X

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

|Function|	Description|
| --- |--- |
|np.array(a) |	Create -dimensional np array from sequence a|
|np.linspace(a,b,N) |	Create 1D np array with N equally spaced values <br> from a to b (inclusively)|
|np.arange(a,b,step) |	Create 1D np array with values from a to b (exclusively) <br> incremented by step|
|np.zeros(N)	| Create 1D np array of zeros of length |
|np.zeros((n,m)) |	Create 2D np array of zeros with  rows and  columns|
|np.ones(N) |	Create 1D np array of ones of length |
|np.ones((n,m))|	Create 2D np array of ones with  rows and  columns|
|np.eye(N)	| Create 2D np array with  rows and  columns  <br> with ones on the diagonal  (ie. the identity matrix of size )|
|np.concatenate( )|Join a sequence of arrays along an existing axis|
|np.hstack( )|Stack arrays in sequence horizontally(column wise)|
|np.vstack( )|Stack arrays in sequence vertically(row wise)|
|np.column_stack( )|Stack 1-D arrays as columns into a 2-D array|
|np.random.normal() | Draw random samples from a normal (Gaussian) distribution. |
|np.linalg.inv() | Compute the (multiplicative) inverse of a matrix. |
|np.dot() / @  | Matrix Multiplication. |

In [10]:
# Create a 1D NumPy array with 11 equally spaced values from 0 to 1:
x = np.linspace( 0, 1, 11 )
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [11]:
# Create a 1D NumPy array with values from 0 to 20 (exclusively) incremented by 5:
y = np.arange( 0, 20, 5 )
print(y)

[ 0  5 10 15]


In [12]:
# Create a 1D NumPy array of zeros of length 5:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
# Create a 2D NumPy array of zeros of shape ( 5, 10 ) :
M = np.zeros( (10, 10) )
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
# Create a 1D NumPy array of ones of length 7:
w = np.ones(7)
print(w)

[1. 1. 1. 1. 1. 1. 1.]


In [15]:
# Create a 2D NumPy array of ones with 35ows and 25 columns:
N = np.ones( (5, 5) )
print(N)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# Create the identity matrix of size 10:
I = np.eye(10)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [18]:
# Shape
I.shape

(10, 10)

In [19]:
# Size
I.size

100

In [20]:
# Concateante
g = np.array([[5,6],[7,8]])
g

array([[5, 6],
       [7, 8]])

In [21]:
h = np.array([[1,2]])
h

array([[1, 2]])

In [27]:
np.concatenate( (g, h) , axis = 0) # columnas

array([[5, 6],
       [7, 8],
       [1, 2]])

In [36]:
test = np.concatenate( (g, h) , axis = 0) # columnas
print(test.shape)
print("\n")
print(test)

(3, 2)


[[5 6]
 [7 8]
 [1 2]]


In [23]:
h_2 = h.reshape(2, 1)
h_2

array([[1],
       [2]])

In [24]:
g

array([[5, 6],
       [7, 8]])

In [26]:
g_h = np.concatenate((g, h_2), axis = 1) # filas
g_h

array([[5, 6, 1],
       [7, 8, 2]])

In [28]:
sett = np.hstack((g,h_2))
sett

array([[5, 6, 1],
       [7, 8, 2]])

In [29]:
# vstack 
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])

In [30]:
z

array([3, 3, 3])

In [31]:
vstacked = np.vstack( (x, y, z) )
vstacked

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [32]:
vstacked.shape

(3, 3)

In [33]:
vstacked = np.vstack((x,y,z))
print(vstacked)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [34]:
# hstack 
hstacked = np.hstack((x,y,z))
print(hstacked)

[1 1 1 2 2 2 3 3 3]


## Exercise

In [ ]:
import numpy as np

# Supongamos que tenemos datos de un programa social que busca mejorar la nutrición infantil en una comunidad
# Tenemos información sobre la altura y el peso de los niños al inicio y al final del programa

# Etapa 1: Crear los datos

# `altura_inicial` y `peso_inicial` corresponde a la altura y peso (en cm y kg) de 10 niños al inicio del programa
# # Altura entre 90cm y 150cm, peso entre 15kg y 45kg

# Etapa 2: Calcular el IMC inicial

# Calcula el índice de masa corporal (IMC) inicial de los niños. El IMC se calcula como peso / (altura/100)^2.
# Almacena los resultados en `imc_inicial`.

# Etapa 3: Simular cambios en altura y peso

# Supongamos que el programa tiene un efecto positivo en la nutrición de los niños.
# Aumenta la altura en un rango aleatorio entre 2 y 5 cm y el peso en un rango aleatorio entre 1 y 3 kg.

# Etapa 4: Calcular y analizar el cambio en el IMC

# Calcula el IMC final de los niños y almacénalo en `imc_final`.
# Después, calcula la diferencia entre el IMC inicial y el IMC final para cada niño y almacénalo en `diferencia_imc`.