# NumPy

*   Instructor: Victor Fuentes Campos
*   Curso: Fundamentos de Programación en Python para las CCSS y Gestión Pública
*   Adapatado de las clases de Carla Solís y Alexander Quispe

Empecemos con un [video sencillo](https://www.youtube.com/watch?v=Tkv45wgxlEU)

> En adelante, empezamos a usar librarías de Python, que son como súperpoderes que catalizarán nuestras habilidades  de programación en Python. Estas funciona como plugins o extensinoes para hacer nuestro código más eficiente

[NumPy](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html) (Numerical Python) es la biblioteca central para la computación científica en Python. Proporciona un objeto array multidimensional de alto rendimiento y herramientas para trabajar con estos. Si ya estás familiarizado con MATLAB, es posible que encuentres útil este tutorial para comenzar con NumPy.

<img src="https://s3.amazonaws.com/dq-content/289/1.2-m289.gif" width="1000">

No olviden instalar numpy: ```conda install numpy```

In [ ]:
%pip install numpy #(mac/windows)

In [35]:
# En el cmd (windows), terminal (mac) o ananconda prompt (anaconda)
# conda install numpy (para la mayoría)
# o
%pip install numpy #(mac/windows)
# o
# brew install numpy (mac si usaron homebrew)
import numpy as np


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


### Arrays
Un array de NumPy es una cuadrícula de valores, todos del mismo tipo, y se indexa mediante tuples de enteros no negativos. El número de dimensiones es el rango del array; la forma (shape) de un array es un tuple de enteros que indica el tamaño del array a lo largo de cada dimensión.

In [5]:
lst = [1, 2, 3, 4, 5]
lst

[1, 2, 3, 4, 5]

In [2]:
a = np.array( [1, 2, 3, 4, 5] )

In [3]:
a   

array([1, 2, 3, 4, 5])

In [6]:
type(a)

numpy.ndarray

In [7]:
# 1D array
a = np.array( [1, 2, 3, 4, 5] )
print(a)

[1 2 3 4 5]


In [8]:
# 2D array
M = np.array( [ [1, 2, 3], [4, 5, 6] ] )

print(M)

[[1 2 3]
 [4 5 6]]


In [9]:
X = np.array( [ [1, 2, 3, 4], [4, 5, 6, 7] ] )
X

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

|Function|	Description|
| --- |--- |
|np.array(a) |	Create -dimensional np array from sequence a|
|np.linspace(a,b,N) |	Create 1D np array with N equally spaced values <br> from a to b (inclusively)|
|np.arange(a,b,step) |	Create 1D np array with values from a to b (exclusively) <br> incremented by step|
|np.zeros(N)	| Create 1D np array of zeros of length |
|np.zeros((n,m)) |	Create 2D np array of zeros with  rows and  columns|
|np.ones(N) |	Create 1D np array of ones of length |
|np.ones((n,m))|	Create 2D np array of ones with  rows and  columns|
|np.eye(N)	| Create 2D np array with  rows and  columns  <br> with ones on the diagonal  (ie. the identity matrix of size )|
|np.concatenate( )|Join a sequence of arrays along an existing axis|
|np.hstack( )|Stack arrays in sequence horizontally(column wise)|
|np.vstack( )|Stack arrays in sequence vertically(row wise)|
|np.column_stack( )|Stack 1-D arrays as columns into a 2-D array|
|np.random.normal() | Draw random samples from a normal (Gaussian) distribution. |
|np.linalg.inv() | Compute the (multiplicative) inverse of a matrix. |
|np.dot() / @  | Matrix Multiplication. |

In [10]:
# Create a 1D NumPy array with 11 equally spaced values from 0 to 1:
x = np.linspace( 0, 1, 11 )
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [11]:
# Create a 1D NumPy array with values from 0 to 20 (exclusively) incremented by 5:
y = np.arange( 0, 20, 5 )
print(y)

[ 0  5 10 15]


In [ ]:
# Create a 1D NumPy array of zeros of length 5:
z = np.zeros(10)
print(z)

In [12]:
# Create a 2D NumPy array of zeros of shape ( 5, 10 ) :
M = np.zeros( (10, 10) )
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
# Create a 1D NumPy array of ones of length 7:
w = np.ones(7)
print(w)

[1. 1. 1. 1. 1. 1. 1.]


In [14]:
# Create a 2D NumPy array of ones with 35ows and 25 columns:
N = np.ones( (5, 5) )
print(N)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
# Create the identity matrix of size 10:
I = np.eye(10)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [17]:
# Shape
I.shape

(10, 10)

In [18]:
# Size
I.size

100

In [19]:
# Concateante
g = np.array([[5,6],[7,8]])
g

array([[5, 6],
       [7, 8]])

In [20]:
h = np.array([[1,2]])
h

array([[1, 2]])

In [21]:
np.concatenate( (g, h) , axis = 0) # columnas

array([[5, 6],
       [7, 8],
       [1, 2]])

In [22]:
test = np.concatenate( (g, h) , axis = 0) # columnas
print(test.shape)
print("\n")
print(test)

(3, 2)


[[5 6]
 [7 8]
 [1 2]]


In [23]:
h_2 = h.reshape(2, 1)
h_2

array([[1],
       [2]])

In [24]:
g

array([[5, 6],
       [7, 8]])

In [ ]:
g_h = np.concatenate((g, h_2), axis = 1) # filas
g_h

In [ ]:
sett = np.hstack((g,h_2))
sett

In [ ]:
# vstack 
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])

In [ ]:
z

In [ ]:
vstacked = np.vstack( (x, y, z) )
vstacked

In [ ]:
vstacked.shape

In [ ]:
vstacked = np.vstack((x,y,z))
print(vstacked)

In [ ]:
# hstack 
hstacked = np.hstack((x,y,z))
print(hstacked)

## Exercise

In [ ]:
import numpy as np

# Supongamos que tenemos datos de un programa social que busca mejorar la nutrición infantil en una comunidad
# Tenemos información sobre la altura y el peso de los niños al inicio y al final del programa

# Etapa 1: Crear los datos

# `altura_inicial` y `peso_inicial` corresponde a la altura y peso (en cm y kg) de 10 niños al inicio del programa
# # Altura entre 90cm y 150cm, peso entre 15kg y 45kg

# Etapa 2: Calcular el IMC inicial

# Calcula el índice de masa corporal (IMC) inicial de los niños. El IMC se calcula como peso / (altura/100)^2.
# Almacena los resultados en `imc_inicial`.

# Etapa 3: Simular cambios en altura y peso

# Supongamos que el programa tiene un efecto positivo en la nutrición de los niños.
# Aumenta la altura en un rango aleatorio entre 2 y 5 cm y el peso en un rango aleatorio entre 1 y 3 kg.

# Etapa 4: Calcular y analizar el cambio en el IMC

# Calcula el IMC final de los niños y almacénalo en `imc_final`.
# Después, calcula la diferencia entre el IMC inicial y el IMC final para cada niño y almacénalo en `diferencia_imc`.

In [ ]:
# Etapa 1: Crear los datos

# `altura_inicial` y `peso_inicial` corresponde a la altura y peso (en cm y kg) de 10 niños al inicio del programa
# # Altura entre 90cm y 150cm, peso entre 15kg y 45kg

In [ ]:
altura_inicial = np.random.randint(90, 150, size=100)
peso_inicial = np.random.randint(15,45, size=100)

In [32]:
# Etapa 2: Calcular el IMC inicial

# Calcula el índice de masa corporal (IMC) inicial de los niños. El IMC se calcula como peso / (altura/100)^2.
# Almacena los resultados en `imc_inicial`.

imc_inicial = peso_inicial / (altura_inicial/100)** 2
print(imc_inicial)

[18.93491124 17.34304544 31.43491124 16.62672991 17.22922703 11.2244898
 18.06421537  8.32986256 24.62296091 17.35766713 20.40816327 28.29334541
 16.43535427 35.45706371 19.80739021 23.04526749 19.21565202 35.80729167
 13.07781299 18.10774106 21.03238988 28.11791383 27.100271   23.41311134
 24.02990388 27.96566077 31.105665   23.44045369 29.36957858 10.59247228
 13.8683432  20.57613169 13.43724805 15.49586777 25.13645504 17.75147929
 22.54680914 37.67313019 14.41753172 15.94387755 39.75591716 32.68494898
 30.51035503 10.41460028 25.26753864 24.00548697 33.93345273 15.68473679
 37.75124987 29.296875   19.321338   19.97621879 15.64868698 16.56804734
 19.65973535 14.8294612  39.88919668 48.14814815 13.20357964 27.75951494
 28.42223544 10.20408163  9.78042936 15.86986709 20.64177144 27.54820937
 20.64177144 23.04526749 25.83979328 31.23698459 36.68442659 23.44045369
 15.52227904 33.28402367 15.500031   24.28026361 22.53944403 12.75510204
 34.56790123 16.87885802 16.27809284 43.93571511 24.

In [39]:
# Etapa 3: Simular cambios en altura y peso

# Supongamos que el programa tiene un efecto positivo en la nutrición de los niños.
# Aumenta la altura en un rango aleatorio entre 2 y 5 cm y el peso en un rango aleatorio entre 1 y 3 kg.

altura_final = altura_inicial + np.random.randint(2,5,100)
peso_final = peso_inicial + np.random.randint(1,3, 100)

In [41]:
# Etapa 4: Calcular y analizar el cambio en el IMC

# Calcula el IMC final de los niños y almacénalo en `imc_final`.
# Después, calcula la diferencia entre el IMC inicial y el IMC final para cada niño y almacénalo en `diferencia_imc`.

imc_final = peso_final / (altura_final/100)** 2
diferencia_imc = imc_final - imc_inicial

In [42]:
print(diferencia_imc)

[ 0.0044827   0.38548642 -0.86455575  0.0329952  -0.1364803   0.51202544
  0.02612326  0.55902633  0.21449982 -0.46894504 -0.35828308 -0.66022818
  0.23058143 -0.76672599  0.03260979  0.39764369  0.61905872 -1.80729167
  0.42527343  0.21787622  0.52812524 -0.68307158 -0.01536297  0.14693578
 -0.02441691 -0.68560621 -0.53530951  0.2596325  -1.20957858  0.15732616
  1.26159628 -0.64628475  0.87076444  0.09780566  0.13504281  0.06986177
 -0.77810165  0.58810905  1.00196942  0.40570628  0.29392264 -0.36731278
 -0.81343827  0.67722071 -0.1310836  -0.4684364  -1.61621978  0.95727504
 -1.93260533  0.29194247  1.04987069 -0.60772187  0.52253776  0.1394599
 -0.26875575  0.87984828 -1.11764275 -1.74706168 -0.0679069  -0.219087
  0.37776456  0.70645199  0.07132519  0.08059266  0.35895902 -0.63548349
 -0.64177144 -0.78969066 -0.013347   -1.44075237  0.34949312  0.6664935
 -0.37338707 -1.56248732  0.47630036  0.09646769  0.22330311  0.62183018
 -1.74762056  0.47899523 -0.40822575 -2.48603927  0.675

In [43]:
np.sum(diferencia_imc>0)

56

In [44]:
np.sum(diferencia_imc<=0)

44